import "./globals.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { cn } from "@/app/lib/utils";

import HeaderComponent from "./_components/Header-Component/Header-Component";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "The Curated Archive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", poppins.className)}>
      <body className="flex min-h-full flex-col bg-[#dedee6]">
        <HeaderComponent />
        {children}
      </body>
    </html>
  );
}
